rings = 2
init = "spot"
b3 = 0.0
b2 = 0.699999988079071
dt = 0.10000000149011612
w1 = 0.15000000596046448
w3 = 0.10000000149011612
w2 = 0.11999999731779099
mu = 0.15000000596046448
growth_kind = "gaussian"
sigma = 0.014999999664723873
backend = "fft"
steps_per_tick = 1
r1 = 0.44999998807907104
r2 = 0.75
radius = 59
integrator_kind = "RK2"
seed = 1
noise_amp = 0.05000000074505806
r3 = 0.8500000238418579
b1 = 1.0
